package user;


import java.io.*;
import java.util.ArrayList;
import business.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class DeleteDevice extends javax.swing.JFrame {

    DefaultTableModel tblModel;
    public DeleteDevice() {
        initComponents();
        setLocationRelativeTo(this);
        
                       
        tblModel = new DefaultTableModel();
        tbdeviceData.setModel(tblModel);
        
        tblModel.addColumn("Device ID");
        tblModel.addColumn("Category");
        tblModel.addColumn("Device Name");
        tblModel.addColumn("Price");
        tblModel.addColumn("Quintity");        
        tblModel.setRowCount(0);
        
        try{
            BufferedReader de = new BufferedReader(new FileReader("Device.txt"));
            String line;
            while((line=de.readLine())!=null){
                if(line.equals("")){
                    continue;
                }
                else{
                    String[] data =line.split(",");
                    tblModel.addRow(new Object[]{data[0],data[4],data[1],data[2],data[3]});
                }
            }
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtdeviceID = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdeviceData = new javax.swing.JTable();
        btnrefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("APPLE I STORE-DELETE DEVICE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Device ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 135, -1, -1));

        txtdeviceID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtdeviceID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtdeviceID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdeviceIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtdeviceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 134, 172, -1));

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 91, -1));

        btnCancel1.setBackground(new java.awt.Color(204, 255, 204));
        btnCancel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel1.setText("Back Main Menu");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 170, -1));

        jScrollPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jScrollPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tbdeviceData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbdeviceData);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 244, 649, 349));

        btnrefresh.setBackground(new java.awt.Color(102, 255, 102));
        btnrefresh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/inf.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdeviceIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdeviceIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdeviceIDActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String deviceID =txtdeviceID.getText();
        delete(deviceID);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jScrollPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jScrollPane1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1AncestorAdded

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        this.setVisible(false);
        DeleteDevice vaUI = new DeleteDevice();
        vaUI.setVisible(true);
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        this.setVisible(false);
        MenuSelect Menu = new MenuSelect ();
        Menu.setVisible(true);
    }//GEN-LAST:event_btnCancel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteDevice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteDevice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteDevice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteDevice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteDevice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdeviceData;
    private javax.swing.JTextField txtdeviceID;
    // End of variables declaration//GEN-END:variables

public static void delete(String deviceID){
        String data;
        boolean deleted = false;
        ArrayList arr=new ArrayList<>();

        try{

            BufferedReader de = new BufferedReader(new FileReader("Device.txt"));


            while((data = de.readLine())!=null){
                if(data.equals("")){
                    continue;
                }
                else{
                    String[] sData = data.split(",");

                    if(sData[0].equals(deviceID)){
                        deleted = true;
                        continue;
                    }
                    else{
                        int DeviceID = Integer.valueOf(sData[0]);
                        String deviceName = sData[1];
                        String price = sData[2];
                        int qnty = Integer.valueOf(sData[3]);
                        String Category = sData[4];

                        device dk =new device(DeviceID,deviceName,price,qnty,Category);
                        arr.add(dk.Print());

                    }
                }
            }
            if(deleted){
                BufferedWriter dev;
                dev =new BufferedWriter(new FileWriter("Device.txt"));
                dev.write("");
                dev.close();
                int i = 0;
                while(i<arr.size()){
                    String line =String.valueOf(arr.get(i));
                    dev =new BufferedWriter(new FileWriter("Device.txt",true));
                    dev.append("\n"+line);
                    dev.close();
                    i++;
                }
                JOptionPane.showMessageDialog(null, "Deleted Sucessfully!");
            }
            else{
                JOptionPane.showMessageDialog(null, "Not Deleted!");
            }
        }
        catch(IOException e){
            System.out.print(e.getMessage());
        }
    }
}
