package user;
import java.io.*;
import javax.swing.JOptionPane;
public class SearchDeviceChy extends javax.swing.JFrame {

    
    public SearchDeviceChy() {
          initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        cmbCondition = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("IPHONE STORE-SEARCH DEVICE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 123, 285, -1));

        cmbCondition.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbCondition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Device ID", "Device Name" }));
        cmbCondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbConditionActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 121, 133, -1));

        btnSearch.setBackground(new java.awt.Color(0, 204, 0));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 120, -1, -1));

        btnCancel1.setBackground(new java.awt.Color(204, 255, 204));
        btnCancel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel1.setText("Back Main Menu");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 170, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/green clean smartphone facebook post.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -160, 730, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void cmbConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbConditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbConditionActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        search();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        this.setVisible(false);
        MenuCashiyer Menu = new MenuCashiyer ();
        Menu.setVisible(true);
    }//GEN-LAST:event_btnCancel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchDeviceChy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchDeviceChy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchDeviceChy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchDeviceChy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchDeviceChy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbCondition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    public void search(){
        String input = txtSearch.getText();
        String filter = (cmbCondition.getSelectedItem()).toString();
        
        try{
            BufferedReader dr = new BufferedReader(new FileReader("Device.txt"));
            String Data;
            
            while((Data = dr.readLine())!=null){
                if(Data.equals("")){
                    continue;
                }
                else{
                    String[] line = Data.split(",");
                    if(filter.equalsIgnoreCase("Device ID")){
                        if(line[0].equals(input)){
                            JOptionPane.showMessageDialog
              (rootPane,"Device ID :"+line[0]+"\n"+"Device Name :"+line[1]+"\n"+"Price :"+line[2]+"\n"
                                                 +"Quintity :"+line[3]+"\n"+"Catagory :"+line[4]+"\n");
                            return;
                        }
                    }
                    else{
                        if(line[1].equals(input)){
                            JOptionPane.showMessageDialog
              (rootPane,"Device ID :"+line[0]+"\n"+"Device Name :"+line[1]+"\n"+"Price :"+line[2]+"\n"
                                                 +"Quintity :"+line[3]+"\n"+"Catagory :"+line[4]+"\n");
                            return;
                        }
                    }
                }
            }
            JOptionPane.showMessageDialog(rootPane,"Device Not Found!");
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

}
