package user;

import java.io.*;
import javax.swing.JOptionPane;
public class UsearAdd extends javax.swing.JFrame {

   
    public UsearAdd() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnManager = new javax.swing.JRadioButton();
        btnClient = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        MainMenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("APPLE ISTORE-USER ADD");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 98, 121, -1));

        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 95, 220, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 147, 121, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 144, 220, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 197, 121, -1));

        btnManager.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnManager.setText("Manager");
        btnManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerActionPerformed(evt);
            }
        });
        getContentPane().add(btnManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 193, 110, -1));

        btnClient.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClient.setText("Cashiyer");
        btnClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientActionPerformed(evt);
            }
        });
        getContentPane().add(btnClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 98, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 100, -1));

        MainMenu.setBackground(new java.awt.Color(255, 204, 204));
        MainMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MainMenu.setText("Back Main Menu");
        MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuActionPerformed(evt);
            }
        });
        getContentPane().add(MainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 170, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/green clean smartphone facebook post.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void btnManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManagerActionPerformed

    private void btnClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addUser();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuActionPerformed
        this.setVisible(false);
        MenuSelect dUI = new MenuSelect();
        dUI.setVisible(true);
    }//GEN-LAST:event_MainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsearAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsearAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsearAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsearAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsearAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainMenu;
    private javax.swing.JRadioButton btnClient;
    private javax.swing.JRadioButton btnManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
public void addUser(){
        String username =txtUserName.getText();
        String password =txtPassword.getText();
        
        if(username.equals("")||password.equals("")){
            JOptionPane.showMessageDialog(rootPane, "All feilds must filled");
            return;
        }
        if(btnClient.isSelected()){
            try{
                File file = new File("OtherUser.txt");
                if(file.exists()){
                    String data;
                    BufferedReader br = new BufferedReader(new FileReader(file));
                    while((data=br.readLine())!=null){
                        if(data.equals("")){
                           
                        }
                        else{
                            String[] line=data.split(":");
                            if(line[0].equals(username)){
                                JOptionPane.showMessageDialog(rootPane, "Username Exists!");
                                br.close();
                                return;
                            }
                        }
                    }
                    BufferedWriter bw = new BufferedWriter(new FileWriter(file,true));
                    bw.append("\n"+username+":"+password);
                    bw.close();
                    JOptionPane.showMessageDialog(rootPane, "User Created!");
                    return;
                }
                
            }
            catch(IOException e){
                return;
            }
        }
        else{
            try{
                File file = new File("MainUser.txt");
                if(file.exists()){
                    String data;
                    BufferedReader br = new BufferedReader(new FileReader(file));
                    while((data=br.readLine())!=null){
                        if(data.equals("")){
                            
                        }
                        else{
                            String[] line=data.split(":");
                            if(line[0].equals(username)){
                                JOptionPane.showMessageDialog(rootPane, "Username Exists!");
                                br.close();
                                return;
                            }
                        }
                    }
                    BufferedWriter bw = new BufferedWriter(new FileWriter(file,true));
                    bw.append("\n"+username+":"+password);
                    bw.close();
                    JOptionPane.showMessageDialog(rootPane, "User Created!");
                    return;
                }
                
            }
            catch(IOException e){
                return;
            }
        }
    }
}